name: Trigger auto deployment for shuklademo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '"wetherforecastapi/Dockerfile"/**'
    - '.github/workflows/shuklademo-AutoDeployTrigger-140001ce-0269-4b40-bd36-7fa548aa30b9.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SHUKLADEMO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}"wetherforecastapi/Dockerfile" 
          registryUrl: tinkushuklaregistry.azurecr.io
          registryUsername: ${{ secrets.SHUKLADEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHUKLADEMO_REGISTRY_PASSWORD }}
          containerAppName: shuklademo
          resourceGroup: shuklademo
          imageToBuild: tinkushuklaregistry.azurecr.io/shuklademo:${{ github.sha }}
          
            

     

