name: Trigger auto deployment for shuklademo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'wetherforecastapi/**'
    - '.github/workflows/shuklademo-AutoDeployTrigger-261166ce-01ac-46cf-89ca-18d378fdcce3.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SHUKLADEMO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}wetherforecastapi 
          registryUrl: tinkushuklaregistry.azurecr.io
          registryUsername: ${{ secrets.SHUKLADEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHUKLADEMO_REGISTRY_PASSWORD }}
          containerAppName: shuklademo
          resourceGroup: shuklademo
          imageToBuild: tinkushuklaregistry.azurecr.io/shuklademo:${{ github.sha }}
          
            

     

